services:
  web:
    image: caddy:alpine
    container_name: mailysleguilloux-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./site:/srv:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    environment:
      - TZ=Europe/Paris

volumes:
  caddy_data:
